export const CLICK_MAIN_SCREEN = "CLICK_MAIN_SCREEN"
export const TIMEOUT_TO_MAIN_PAGE = "TIMEOUT_TO_MAIN_PAGE"
export const BACK_TO_MAIN_PAGE = "BACK_TO_MAIN_PAGE"
export const FIRST_LOAD = "FIRST_LOAD"
